<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
$mapping = [
    [
        'label' => 'Open Home Page',
        'uri' => '^\/$',
        'title' => 'Home Page',
        'is_service_url' => true,
        'is_storefront' => true,
    ],
    [
        'label' => 'Open Home Page',
        'uri' => '^\/$',
        'title' => 'Home Page\(Catalog Browsing',
        'scenario' => 'Catalog Browsing',
    ],
    [
        'label' => 'Open Home Page',
        'uri' => '^\/$',
        'title' => 'Home Page\(Site Search',
        'scenario' => 'Search',
    ],
    [
        'label' => 'Open Home Page',
        'uri' => '^\/$',
        'title' => 'Home Page\(Quick Order',
        'scenario' => 'QuickOrder',
    ],
    [
        'label' => 'Open Home Page',
        'uri' => '^\/$',
        'title' => 'Home Page\(Requisition List\)',
        'scenario' => 'Requisition List',
    ],
    [
        'label' => 'Open Home Page',
        'uri' => '^\/$',
        'title' => 'Home Page\(Requisition List From Order',
        'scenario' => 'Requisition List From Order',
    ],
    [
        'label' => 'Open Login Page',
        'uri' => '\/customer\/account\/login',
        'title' => 'Open Login Page',
        'is_service_url' => true,
        'is_storefront' => true,
    ],
    [
        'label' => 'Open Login Page',
        'uri' => '\/customer\/account\/login',
        'title' => 'Open Login Page\(Catalog Browsing',
        'scenario' => 'Catalog Browsing',
    ],
    [
        'label' => 'Open Login Page',
        'uri' => '\/customer\/account\/login',
        'title' => 'Open Login Page\(Site Search',
        'scenario' => 'Search',
    ],
    [
        'label' => 'Open Login Page',
        'uri' => '\/customer\/account\/login',
        'title' => 'Open Login Page\(Product Compare',
        'scenario' => 'Compare Products',
    ],
    [
        'label' => 'Open Login Page',
        'uri' => '\/customer\/account\/login',
        'title' => 'Open Login Page\(Quick Order',
        'scenario' => 'QuickOrder',
    ],
    [
        'label' => 'Open Login Page',
        'uri' => '\/customer\/account\/login',
        'title' => 'Open Login Page\(Requisition List\)',
        'scenario' => 'Requisition List',
    ],
    [
        'label' => 'Open Login Page',
        'uri' => '\/customer\/account\/login',
        'title' => 'Open Login Page\(Requisition List From Order',
        'scenario' => 'Requisition List From Order',
    ],
    [
        'label' => 'Ajax Load Login Form',
        'uri' => '\/page_cache\/block\/render',
        'title' => 'Ajax Load Login Form',
        'is_service_url' => true,
        'is_storefront' => true,
    ],
    [
        'label' => 'Ajax Load Login Form',
        'uri' => '\/page_cache\/block\/render',
        'title' => 'Ajax Load Login Form\(Catalog Browsing',
        'scenario' => 'Catalog Browsing',
    ],
    [
        'label' => 'Ajax Load Login Form',
        'uri' => '\/page_cache\/block\/render',
        'title' => 'Ajax Load Login Form\(Site Search',
        'scenario' => 'Search',
    ],
    [
        'label' => 'Ajax Load Login Form',
        'uri' => '\/page_cache\/block\/render',
        'title' => 'Ajax Load Login Form\(Product Compare',
        'scenario' => 'Compare Products',
    ],
    [
        'label' => 'Ajax Load Login Form',
        'uri' => '\/page_cache\/block\/render',
        'title' => 'Ajax Load Login Form\(Quick Order',
        'scenario' => 'QuickOrder',
    ],
    [
        'label' => 'Ajax Load Login Form',
        'uri' => '\/page_cache\/block\/render',
        'title' => 'Ajax Load Login Form\(Requisition List\)',
        'scenario' => 'Requisition List',
    ],
    [
        'label' => 'Ajax Load Login Form',
        'uri' => '\/page_cache\/block\/render',
        'title' => 'Ajax Load Login Form\(Requisition List From Order',
        'scenario' => 'Requisition List From Order',
    ],
    [
        'label' => 'Ajax Load Login Form',
        'uri' => '\/page_cache\/block\/render',
        'title' => 'Ajax Load Login Form\(Negotiable Quote',
        'scenario' => 'Negotiable Quote',
    ],
    [
        'label' => 'Ajax Load Login Form',
        'uri' => '\/page_cache\/block\/render',
        'title' => 'Ajax Load Login Form\(Reorder',
        'scenario' => 'Reorder',
    ],
    [
        'label' => 'Logout Action',
        'uri' => '\/customer\/account\/logout',
        'title' => 'Logout',
        'is_service_url' => true,
        'is_storefront' => true,
    ],
    [
        'label' => 'Logout Action',
        'uri' => '\/customer\/account\/logout',
        'title' => 'Logout\(Catalog Browsing',
        'scenario' => 'Catalog Browsing',
    ],
    [
        'label' => 'Logout Action',
        'uri' => '\/customer\/account\/logout',
        'title' => 'Logout\(Search',
        'scenario' => 'Search',
    ],
    [
        'label' => 'Logout Action',
        'uri' => '\/customer\/account\/logout',
        'title' => 'Logout\(Product Compare',
        'scenario' => 'Compare Products',
    ],
    [
        'label' => 'Logout Action',
        'uri' => '\/customer\/account\/logout',
        'title' => 'Logout\(Quick Order',
        'scenario' => 'QuickOrder',
    ],
    [
        'label' => 'Logout Action',
        'uri' => '\/customer\/account\/logout',
        'title' => 'Logout\(Requisition List\)',
        'scenario' => 'Requisition List',
    ],
    [
        'label' => 'Logout Action',
        'uri' => '\/customer\/account\/logout',
        'title' => 'Logout\(Requisition List From Order',
        'scenario' => 'Requisition List From Order',
    ],
    [
        'label' => 'Logout Action',
        'uri' => '\/customer\/account\/logout',
        'title' => 'Logout\(Negotiable Quote',
        'scenario' => 'Negotiable Quote',
    ],
    [
        'label' => 'Logout Action',
        'uri' => '\/customer\/account\/logout',
        'title' => 'Logout\(Reorder',
        'scenario' => 'Reorder',
    ],
    [
        'label' => 'Login Action',
        'uri' => '\/customer\/account\/loginPost',
        'title' => '^Login\s*\(',
        'is_service_url' => true,
        'is_storefront' => true,
    ],
    [
        'label' => 'Login Action',
        'uri' => '\/customer\/account\/loginPost',
        'title' => '^Login\s*\(Catalog Browsing',
        'scenario' => 'Catalog Browsing',
    ],
    [
        'label' => 'Login Action',
        'uri' => '\/customer\/account\/loginPost',
        'title' => '^Login\s*\(Site Search',
        'scenario' => 'Search',
    ],
    [
        'label' => 'Login Action',
        'uri' => '\/customer\/account\/loginPost',
        'title' => '^Login\s*\(Product Compare',
        'scenario' => 'Compare Products',
    ],
    [
        'label' => 'Login Action',
        'uri' => '\/customer\/account\/loginPost',
        'title' => '^Login\s*\(Quick Order',
        'scenario' => 'QuickOrder',
    ],
    [
        'label' => 'Login Action',
        'uri' => '\/customer\/account\/loginPost',
        'title' => '^Login\s*\(Requisition List',
        'scenario' => 'Requisition List',
    ],
    [
        'label' => 'Login Action',
        'uri' => '\/customer\/account\/loginPost',
        'title' => '^Login\s*\(Requisition List From Order',
        'scenario' => 'Requisition List From Order',
    ],
    [
        'label' => 'Login Action',
        'uri' => '\/customer\/account\/loginPost',
        'title' => '^Login\s*\(Negotiable Quote',
        'scenario' => 'Negotiable Quote',
    ],
    [
        'label' => 'Login Action',
        'uri' => '\/customer\/account\/loginPost',
        'title' => '^Login\s*\(Reorder',
        'scenario' => 'Reorder',
    ],
    [
        'label' => 'Open Category Page',
        'uri' => '\/category-\d+\.html',
        'title' => 'Open Category',
        'is_service_url' => true,
        'is_storefront' => true,
    ],
    [
        'label' => 'Open Category Page',
        'uri' => '\/category-\d+\.html',
        'title' => 'Open Category\(Catalog Browsing',
        'scenario' => 'Catalog Browsing',
    ],
    [
        'label' => 'Open Category Page',
        'uri' => '\/category-\d+\.html',
        'title' => 'Open Category\(Product Compare',
        'scenario' => 'Compare Products',
    ],
    [
        'label' => 'Open Category Page',
        'uri' => '\/category-\d+\.html',
        'title' => 'Open Category\(Requisition List',
        'scenario' => 'Requisition List',
    ],
    [
        'label' => 'Open Category Page',
        'uri' => '\/category-\d+\.html',
        'title' => 'Open Category\(Reorder',
        'scenario' => 'Reorder',
    ],
    [
        'label' => 'Open Simple Product Page',
        'uri' => '\/simple-product-\d+\.html',
        'title' => '^(?:(?:Product\s(?:[0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-3][0-9]|24[0-6])\sView)|'
                . '(?:Simple Product \d+ View))',
        'is_service_url' => true,
    ],
    [
        'label' => 'Open Simple Product Page',
        'uri' => '\/simple-product-\d+\.html',
        'title' => 'Simple Product \d+ View\(Catalog Browsing',
        'scenario' => 'Catalog Browsing',
        'is_storefront' => true,
    ],
    [
        'label' => 'Open Product Page',
        'uri' => '\/(?:configurable|simple)-product-\d+\.html',
        'title' => '^Product \d+ View(\s\d)?\(Search',
        'scenario' => 'Search',
        'is_storefront' => true,
    ],
    [
        'label' => 'Open Simple Product Page',
        'uri' => '\/simple-product-\d+\.html',
        'title' => 'Simple Product \d+ View\(Product Compare',
        'scenario' => 'Compare Products',
        'is_storefront' => true,
    ],
    [
        'label' => 'Open Product Page',
        'uri' => '\/(?:configurable|simple)-product-\d+\.html',
        'title' => 'Product\s\d+\sView\(Requisition List',
        'scenario' => 'Requisition List',
        'is_storefront' => true,
    ],
    [
        'label' => 'Open Configurable Product Page',
        'uri' => '\/configurable-product-\d+\.html',
        'title' => '^(?:(?:Product\s(?:24[7-9]|2[5-9][0-9]|300)\sView)|(?:Configurable Product \d+ View))',
        'is_service_url' => true,
    ],
    [
        'label' => 'Open Configurable Product Page',
        'uri' => '\/configurable-product-\d+\.html',
        'title' => 'Configurable Product \d+ View\(Catalog Browsing',
        'scenario' => 'Catalog Browsing',
        'is_storefront' => true,
    ],
    [
        'label' => 'Open Configurable Product Page',
        'uri' => '\/configurable-product-\d+\.html',
        'title' => 'Configurable Product \d+ View\(Product Compare',
        'scenario' => 'Compare Products',
        'is_storefront' => true,
    ],
    [
        'label' => 'Open Configurable Product Page',
        'uri' => '\/configurable-product-\d+\.html',
        'title' => 'Configurable Product \d+ View\(Reorder',
        'scenario' => 'Reorder',
        'is_storefront' => true,
    ],
    [
        'label' => 'Ajax Product Review',
        'uri' => '\/review\/product\/listAjax\/id\/\d+',
        'title' => 'Ajax Review.*\(Search',
        'scenario' => 'Search',
        'is_storefront' => true,
    ],
    [
        'label' => 'Quick Search',
        'uri' => '\/catalogsearch\/result',
        'title' => 'Search\(SearchQuick\)',
        'scenario' => 'Search',
        'is_storefront' => true,
    ],
    [
        'label' => 'Quick Search With Filter',
        'uri' => '\/catalogsearch\/result',
        'title' => 'Search(?:\s\d)?\(SearchQuickWithFilter\)',
        'scenario' => 'Search',
        'is_storefront' => true,
    ],
    [
        'label' => 'Filter By Attribute',
        'uri' => '\/catalogsearch\/result',
        'title' => 'Filter by Attribute',
        'scenario' => 'Search',
        'is_storefront' => true,
    ],
    [
        'label' => 'Open Advanced Search Page',
        'uri' => '\/catalogsearch\/advanced',
        'title' => 'Open Advanced Search',
        'scenario' => 'Search',
        'is_storefront' => true,
    ],
    [
        'label' => 'Perform Advanced Search',
        'uri' => '\/catalogsearch\/advanced\/result',
        'title' => '^Search\(SearchAdvanced\)',
        'scenario' => 'Search',
        'is_storefront' => true,
    ],
    [
        'label' => 'Add Simple Product To Compare List',
        'uri' => '\/catalog\/product_compare\/add',
        'title' => '^(Simple )?Product .* Comparison Add',
        'scenario' => 'Compare Products',
        'is_storefront' => true,
    ],
    [
        'label' => 'Add Configurable Product To Compare List',
        'uri' => '\/catalog\/product_compare\/add',
        'title' => 'Configurable Product .* Comparison Add',
        'scenario' => 'Compare Products',
        'is_storefront' => true,
    ],
    [
        'label' => 'Load Customer Section',
        'uri' => '\/customer\/section\/load',
        'title' => '(?:Customer Section )?Load.*Company Admin',
        'is_service_url' => true,
        'is_storefront' => true,
    ],
    [
        'label' => 'Load Customer Section',
        'uri' => '\/customer\/section\/load',
        'title' => 'Customer Section Load\(Product Compare',
        'scenario' => 'Compare Products',
    ],
    [
        'label' => 'Load Customer Section',
        'uri' => '\/customer\/section\/load',
        'title' => 'Load Company Admin\(Quick Order',
        'scenario' => 'QuickOrder',
    ],
    [
        'label' => 'Load Customer Section',
        'uri' => '\/customer\/section\/load',
        'title' => 'Load Company Admin\(Requisition List\)',
        'scenario' => 'Requisition List',
    ],
    [
        'label' => 'Load Customer Section',
        'uri' => '\/customer\/section\/load',
        'title' => 'Load Company Admin\(Requisition List From Order',
        'scenario' => 'Requisition List From Order',
    ],
    [
        'label' => 'Load Customer Section',
        'uri' => '\/customer\/section\/load',
        'title' => 'Load Company Admin\(Negotiable Quote',
        'scenario' => 'Negotiable Quote',
    ],
    [
        'label' => 'Load Customer Section',
        'uri' => '\/customer\/section\/load',
        'title' => 'Load Company Admin\(Reorder',
        'scenario' => 'Reorder',
    ],
    [
        'label' => 'Compare Products',
        'uri' => '\/catalog\/product_compare\/index\/items\/',
        'title' => 'Compare Products\(.*',
        'scenario' => 'Compare Products',
        'is_storefront' => true,
    ],
    [
        'label' => 'Remove Products From Comparison',
        'uri' => '\/catalog\/product_compare\/clear',
        'title' => 'Compare Products Clear',
        'scenario' => 'Compare Products',
        'is_storefront' => true,
    ],
    [
        'label' => 'Open QuickOrder Page',
        'uri' => '\/quickorder',
        'title' => 'Quickorder Open',
        'scenario' => 'QuickOrder',
        'is_storefront' => true,
    ],
    [
        'label' => 'QuickOrder Suggest Product',
        'uri' => '\/quickorder\/ajax\/product_suggest',
        'title' => 'Quickorder Suggest Product',
        'scenario' => 'QuickOrder',
        'is_storefront' => true,
    ],
    [
        'label' => 'QuickOrder Search Product',
        'uri' => '\/quickorder\/ajax\/search',
        'title' => 'Quickorder Search Product',
        'scenario' => 'QuickOrder',
        'is_storefront' => true,
    ],
    [
        'label' => 'QuickOrder Multiple Search',
        'uri' => '\/quickorder\/ajax\/search',
        'title' => 'Quickorder Search Multiple',
        'scenario' => 'QuickOrder',
        'is_storefront' => true,
    ],
    [
        'label' => 'QuickOrder Add To Cart',
        'uri' => '\/quickorder\/sku\/uploadfile',
        'title' => 'Quickorder Add To Cart',
        'scenario' => 'QuickOrder',
        'is_requisition' => true,
        'is_storefront' => true,
    ],
    [
        'label' => 'Open Configurable Product Configuration Page',
        'uri' => '\/checkout\/cart\/configureFailed\/id',
        'title' => 'Open Configurable Product Configuration',
        'scenario' => 'QuickOrder',
        'is_storefront' => true,
    ],
    [
        'label' => 'Configure Configurable Product Configuration',
        'uri' => '\/checkout\/cart\/updateFailedItemOptions\/id',
        'title' => 'Configure Configurable Product',
        'scenario' => 'QuickOrder',
        'is_storefront' => true,
    ],
    [
        'label' => 'Checkout Estimate Shipping Methods',
        'uri' => '\/rest\/default\/V1\/carts\/mine\/estimate-shipping-methods-by-address-id',
        'title' => 'Checkout Estimate Shipping Methods\(Quick Order',
        'scenario' => 'QuickOrder',
        'is_storefront' => true,
    ],
    [
        'label' => 'Start Checkout',
        'uri' => '\/checkout\/$',
        'title' => 'Checkout Start\(Quick Order',
        'scenario' => 'QuickOrder',
        'is_storefront' => true,
    ],
    [
        'label' => 'Checkout Billing/Shipping Information',
        'uri' => '\/rest\/default\/V1\/carts\/mine\/shipping-information',
        'title' => 'Checkout Billing\/Shipping Information\(Quick Order',
        'scenario' => 'QuickOrder',
        'is_storefront' => true,
    ],
    [
        'label' => 'Checkout Payment/Info Place Order',
        'uri' => '\/rest\/default\/V1\/carts\/mine\/payment-information',
        'title' => 'Checkout Payment Info\/Place Order\(Quick Order',
        'scenario' => 'QuickOrder',
        'is_storefront' => true,
    ],
    [
        'label' => 'Checkout Success Page',
        'uri' => '\/checkout\/onepage\/success',
        'title' => 'Checkout Success',
        'is_service_url' => true,
        'is_storefront' => true,
    ],
    [
        'label' => 'Checkout Success Page',
        'uri' => '\/checkout\/onepage\/success',
        'title' => 'Checkout Success\(Quick Order',
        'scenario' => 'QuickOrder',
    ],
    [
        'label' => 'Checkout Success Page',
        'uri' => '\/checkout\/onepage\/success',
        'title' => 'Checkout Success\(Requisition List\)',
        'scenario' => 'Requisition List',
    ],
    [
        'label' => 'Checkout Success Page',
        'uri' => '\/checkout\/onepage\/success',
        'title' => 'Checkout Success\(Requisition List From Order',
        'scenario' => 'Requisition List From Order',
    ],
    [
        'label' => 'Checkout Success Page',
        'uri' => '\/checkout\/onepage\/success',
        'title' => 'Checkout Success\(Negotiable Quote',
        'scenario' => 'Negotiable Quote',
    ],
    [
        'label' => 'Checkout Success Page',
        'uri' => '\/checkout\/onepage\/success',
        'title' => 'Checkout Success\(Reorder',
        'scenario' => 'Reorder',
    ],
    [
        'label' => 'Delete Item From Shopping Cart',
        'uri' => '\/checkout\/cart\/delete',
        'title' => '(?:Delete From Cart|Remove Item)',
        'is_service_url' => true,
        'is_storefront' => true,
    ],
    [
        'label' => 'Create Requisition List',
        'uri' => '\/rest\/V1\/requisition_lists',
        'title' => 'Create Requisition List\(Requisition List\)',
        'scenario' => 'Requisition List',
        'is_storefront' => true,
    ],
    [
        'label' => 'Create Requisition List',
        'uri' => '\/rest\/V1\/requisition_lists',
        'title' => 'Create Requisition List\(Requisition List From Order\)',
        'scenario' => 'Requisition List From Order',
        'is_storefront' => true,
    ],
    [
        'label' => 'Add Product To Requisition List',
        'uri' => '\/requisition_list\/item\/add',
        'title' => '- Add To Requisition List',
        'scenario' => 'Requisition List',
        'is_storefront' => true,
    ],
    [
        'label' => 'View Requisition List',
        'uri' => '\/requisition_list\/requisition\/view\/requisition_id\/',
        'title' => 'Requisition List View\(Requisition List\)',
        'scenario' => 'Requisition List',
        'is_storefront' => true,
    ],
    [
        'label' => 'Requisition List Add To Cart',
        'uri' => '\/requisition_list\/item\/addToCart',
        'title' => '^Add To Cart\(Requisition List\)',
        'scenario' => 'Requisition List',
        'is_requisition' => true,
        'is_storefront' => true,
    ],
    [
        'label' => 'Checkout Estimate Shipping Methods',
        'uri' => '\/rest\/default\/V1\/carts\/mine\/estimate-shipping-methods-by-address-id',
        'title' => 'Checkout Estimate Shipping Methods\(Requisition List\)',
        'scenario' => 'Requisition List',
        'is_storefront' => true,
    ],
    [
        'label' => 'Start Checkout',
        'uri' => '\/checkout\/cart\/$',
        'title' => 'Checkout Start\(Requisition List\)',
        'scenario' => 'Requisition List',
        'is_storefront' => true,
    ],
    [
        'label' => 'Checkout Billing/Shipping Information',
        'uri' => '\/rest\/default\/V1\/carts\/mine\/shipping-information',
        'title' => 'Checkout Billing\/Shipping Information\(Requisition List\)',
        'scenario' => 'Requisition List',
        'is_storefront' => true,
    ],
    [
        'label' => 'Checkout Payment/Info Place Order',
        'uri' => '\/rest\/default\/V1\/carts\/mine\/payment-information',
        'title' => 'Checkout Payment Info\/Place Order\(Requisition List\)',
        'scenario' => 'Requisition List',
        'is_storefront' => true,
    ],
    [
        'label' => 'Open Orders History',
        'uri' => '\/sales\/order\/history',
        'title' => 'Open Order History\(Requisition List From Order',
        'scenario' => 'Requisition List From Order',
        'is_storefront' => true,
    ],
    [
        'label' => 'Open Orders History',
        'uri' => '\/sales\/order\/history',
        'title' => 'Open Order History\(Reorder',
        'scenario' => 'Reorder',
        'is_storefront' => true,
    ],
    [
        'label' => 'View Order',
        'uri' => '\/sales\/order\/view\/order_id',
        'title' => 'View Order\(Requisition List From Order',
        'scenario' => 'Requisition List From Order',
        'is_storefront' => true,
    ],
    [
        'label' => 'View Order',
        'uri' => '\/sales\/order\/view\/order_id',
        'title' => 'View Order\(Reorder',
        'scenario' => 'Reorder',
        'is_storefront' => true,
    ],
    [
        'label' => 'Copy Order Items To Requisition List',
        'uri' => '\/requisition_list\/item\/copy_fromOrder',
        'title' => 'Copy Order Items To Requisition List',
        'scenario' => 'Requisition List From Order',
        'is_storefront' => true,
    ],
    [
        'label' => 'View Requisition List',
        'uri' => '\/requisition_list\/requisition\/view\/requisition_id\/',
        'title' => 'Requisition List View\(Requisition List From Order',
        'scenario' => 'Requisition List From Order',
        'is_storefront' => true,
    ],
    [
        'label' => 'Requisition List Add To Cart',
        'uri' => '\/requisition_list\/item\/addToCart',
        'title' => '^Add To Cart\(Requisition List From Order\)',
        'scenario' => 'Requisition List From Order',
        'is_requisition' => true,
        'is_storefront' => true,
    ],
    [
        'label' => 'Checkout Estimate Shipping Methods',
        'uri' => '\/rest\/default\/V1\/carts\/mine\/estimate-shipping-methods-by-address-id',
        'title' => 'Checkout Estimate Shipping Methods\(Requisition List From Order',
        'scenario' => 'Requisition List From Order',
        'is_storefront' => true,
    ],
    [
        'label' => 'Start Checkout',
        'uri' => '\/checkout\/$',
        'title' => 'Checkout Start\(Requisition List From Order',
        'scenario' => 'Requisition List From Order',
        'is_storefront' => true,
    ],
    [
        'label' => 'Checkout Billing/Shipping Information',
        'uri' => '\/rest\/default\/V1\/carts\/mine\/shipping-information',
        'title' => 'Checkout Billing\/Shipping Information\(Requisition List From Order',
        'scenario' => 'Requisition List From Order',
        'is_storefront' => true,
    ],
    [
        'label' => 'Checkout Payment/Info Place Order',
        'uri' => '\/rest\/default\/V1\/carts\/mine\/payment-information',
        'title' => 'Checkout Payment Info\/Place Order\(Requisition List From Order',
        'scenario' => 'Requisition List From Order',
        'is_storefront' => true,
    ],
    [
        'label' => 'Add Product To Cart',
        'uri' => '\/checkout\/cart\/add\/uenc',
        'title' => 'Product \d+ - Add To Cart\(Negotiable Quote',
        'scenario' => 'Negotiable Quote',
        'is_storefront' => true,
    ],
    [
        'label' => 'Add Configurable Product To Cart',
        'uri' => '\/checkout\/cart\/add\/uenc',
        'title' => 'Configurable Product \d+ Add To Cart\(Reorder',
        'scenario' => 'Reorder',
        'is_storefront' => true,
    ],
    [
        'label' => 'Start Checkout',
        'uri' => '\/checkout\/cart\/$',
        'title' => 'Open Cart\(Negotiable Quote',
        'scenario' => 'Negotiable Quote',
        'is_storefront' => true,
    ],
    [
        'label' => 'Check Negotiable Quote Discount',
        'uri' => '\/negotiable_quote\/quote\/checkDiscount',
        'title' => 'Quote Check Discount',
        'scenario' => 'Negotiable Quote',
        'is_storefront' => true,
    ],
    [
        'label' => 'Request Negotiable Quote',
        'uri' => '\/negotiable_quote\/quote\/create\/quote_id\/',
        'title' => 'Request Quote',
        'scenario' => 'Negotiable Quote',
        'is_requisition' => true,
        'is_storefront' => true,
    ],
    [
        'label' => 'Open Negotiable Quotes Grid',
        'uri' => '\/negotiable_quote\/ui\/render\/',
        'title' => 'Open Quotes',
        'scenario' => 'Negotiable Quote',
        'is_storefront' => true,
    ],
    [
        'label' => 'Open Negotiable Quote',
        'uri' => '\/negotiable_quote\/quote\/view\/quote_id\/',
        'title' => '^Open Quote',
        'scenario' => 'Negotiable Quote',
        'is_storefront' => true,
    ],
    [
        'label' => 'Recalculate Negotiable Quote',
        'uri' => '\/negotiable_quote\/quote\/recalculate\/',
        'title' => 'Quote Recalculate',
        'scenario' => 'Negotiable Quote',
        'is_storefront' => true,
    ],
    [
        'label' => 'Checkout Negotiable Quote',
        'uri' => '\/negotiable_quote\/quote\/checkout\/negotiableQuoteId\/',
        'title' => 'Quote Checkout Start',
        'scenario' => 'Negotiable Quote',
        'is_storefront' => true,
    ],
    [
        'label' => 'Checkout Billing/Shipping Information',
        'uri' => '\/rest\/default\/V1\/carts\/mine\/shipping-information',
        'title' => 'Checkout Billing\/Shipping Information\(Negotiable Quote',
        'scenario' => 'Negotiable Quote',
        'is_storefront' => true,
    ],
    [
        'label' => 'Checkout Payment/Info Place Order',
        'uri' => '\/rest\/default\/V1\/carts\/mine\/payment-information',
        'title' => 'Checkout Payment Info\/Place Order\(Negotiable Quote\)',
        'scenario' => 'Negotiable Quote',
        'is_storefront' => true,
    ],
    [
        'label' => 'Reorder',
        'uri' => '\/sales\/order\/reorder\/order_id\/',
        'title' => 'Reorder\(Reorder',
        'scenario' => 'Reorder',
        'is_requisition' => true,
        'is_storefront' => true,
    ],
    [
        'label' => 'Update Cart Qty',
        'uri' => '\/checkout\/cart\/updatePost',
        'title' => 'Update Cart Qty\(Reorder',
        'scenario' => 'Reorder',
        'is_storefront' => true,
    ],
    [
        'label' => 'Open Update Configurable Product In Cart',
        'uri' => '\/checkout\/cart\/configure\/id\/',
        'title' => 'Open Update Configurable Product In Cart\(Reorder',
        'scenario' => 'Reorder',
        'is_storefront' => true,
    ],
    [
        'label' => 'Update Configurable Product In Cart',
        'uri' => '\/checkout\/cart\/updateItemOptions\/id\/',
        'title' => '^Update Configurable Product In Cart\(Reorder',
        'scenario' => 'Reorder',
        'is_storefront' => true,
    ],
    [
        'label' => 'Checkout Estimate Shipping Methods',
        'uri' => '\/rest\/default\/V1\/carts\/mine\/estimate-shipping-methods-by-address-id',
        'title' => 'Checkout Estimate Shipping Methods\(Reorder',
        'scenario' => 'Reorder',
        'is_storefront' => true,
    ],
    [
        'label' => 'Open Cart',
        'uri' => '\/checkout\/(?:cart)?$',
        'title' => '(?:Checkout Start|Open Cart)\(Reorder',
        'scenario' => 'Reorder',
        'is_storefront' => true,
    ],
    [
        'label' => 'Checkout Billing/Shipping Information',
        'uri' => '\/rest\/default\/V1\/carts\/mine\/shipping-information',
        'title' => 'Checkout Billing\/Shipping Information\(Reorder',
        'scenario' => 'Reorder',
        'is_storefront' => true,
    ],
    [
        'label' => 'Checkout Payment/Info Place Order',
        'uri' => '\/rest\/default\/V1\/carts\/mine\/payment-information',
        'title' => 'Checkout Payment Info\/Place Order\(Reorder\)',
        'scenario' => 'Reorder',
        'is_storefront' => true,
    ],
    [
        'label' => 'Login To Admin Panel',
        'uri' => '\/admin',
        'title' => '- Login$',
        'is_service_url' => true
    ],
    [
        'label' => 'Login To Admin Panel - Submit Form',
        'uri' => '\/admin\/admin\/dashboard\/',
        'title' => '- Login Submit Form',
        'is_service_url' => true
    ],
    [
        'label' => 'Admin - Edit Simple Product',
        'uri' => '\/admin\/catalog\/product\/edit\/id',
        'title' => 'Admin Edit Product - Edit Simple Product$',
        'scenario' => 'Admin - Edit Product',
    ],
    [
        'label' => 'Admin - Validate Simple Product',
        'uri' => '\/admin\/catalog\/product\/validate\/id',
        'title' => 'Admin Edit Product - Edit Simple Product Validate',
        'scenario' => 'Admin - Edit Product',
    ],
    [
        'label' => 'Admin - Save Simple Product',
        'uri' => '\/admin\/catalog\/product\/save\/id',
        'title' => 'Admin Edit Product - Edit Simple Product Save',
        'scenario' => 'Admin - Edit Product',
    ],
    [
        'label' => 'Admin - Edit Configurable Product',
        'uri' => '\/admin\/catalog\/product\/edit\/id',
        'title' => 'Admin Edit Product - Edit Configurable Product$',
        'scenario' => 'Admin - Edit Product',
    ],
    [
        'label' => 'Admin - Validate Configurable Product',
        'uri' => '\/admin\/catalog\/product\/validate\/id',
        'title' => 'Admin Edit Product - Edit Configurable Product Validate',
        'scenario' => 'Admin - Edit Product',
    ],
    [
        'label' => 'Admin - Save Configurable Product',
        'uri' => '\/admin\/catalog\/product\/save\/id',
        'title' => 'Admin Edit Product - Edit Configurable Product Save',
        'scenario' => 'Admin - Edit Product',
    ],
    [
        'label' => 'Admin - Open Product Page',
        'uri' => '\/admin\/catalog\/product\/',
        'title' => 'Admin Create Product - Catalog Product',
        'scenario' => 'Admin - Create Product',
    ],
    [
        'label' => 'Admin - Create New Bundle Product',
        'uri' => '\/admin\/catalog\/product\/new\/set\/4\/type\/bundle\/',
        'title' => 'Admin Create Product - New Bundle Product$',
        'scenario' => 'Admin - Create Product',
    ],
    [
        'label' => 'Admin - Validate New Bundle Product',
        'uri' => '\/admin\/catalog\/product\/validate\/set\/4\/',
        'title' => 'Admin Create Product - New Bundle Product Validate',
        'scenario' => 'Admin - Create Product',
    ],
    [
        'label' => 'Admin - Save New Bundle Product',
        'uri' => '\/admin\/catalog\/product\/save\/set\/4\/type\/bundle\/back\/edit\/active_tab\/product-details\/',
        'title' => 'Admin Create Product - New Bundle Product Save',
        'scenario' => 'Admin - Create Product',
    ],
    [
        'label' => 'Admin - Create New Configurable Product',
        'uri' => '\/admin\/catalog\/product\/new\/set\/4\/type\/configurable\/',
        'title' => 'Admin Create Product - New Configurable Product$',
        'scenario' => 'Admin - Create Product',
    ],
    [
        'label' => 'Admin - Create Product Options',
        'uri' => '\/admin\/catalog\/product_attribute\/createOptions\/\?isAjax=true',
        'title' => 'Admin Create Product - Create Options',
        'scenario' => 'Admin - Create Product',
    ],
    [
        'label' => 'Admin - Validate New Configurable Product',
        'uri' => '\/admin\/catalog\/product\/validate\/set\/4\/',
        'title' => 'Admin Create Product - New Configurable Product Validate',
        'scenario' => 'Admin - Create Product',
    ],
    [
        'label' => 'Admin - Save New Configurable Product',
        'uri' => '\/admin\/catalog\/product\/save\/set\/4\/type\/configurable'
                . '\/back\/edit\/active_tab\/product-details\/',
        'title' => 'Admin Create Product - New Configurable Product Save',
        'scenario' => 'Admin - Create Product',
    ],
    [
        'label' => 'Admin - Create New Downloadable Product',
        'uri' => '\/admin\/catalog\/product\/new\/set\/4\/type\/downloadable\/',
        'title' => 'Admin Create Product - New Downloadable Product$',
        'scenario' => 'Admin - Create Product',
    ],
    [
        'label' => 'Admin - Add Original File To Downloadable Product',
        'uri' => '\/admin\/downloadable_file\/upload\/type\/links\/\?isAjax=true',
        'title' => 'Admin Create Product - New Downloadable Upload Original File',
        'scenario' => 'Admin - Create Product',
    ],
    [
        'label' => 'Admin - Add Sample File To Downloadable Product',
        'uri' => '\/admin\/downloadable_file\/upload\/type\/samples\/\?isAjax=true',
        'title' => 'Admin Create Product - New Downloadable Upload Sample File',
        'scenario' => 'Admin - Create Product',
    ],
    [
        'label' => 'Admin - Validate New Downloadable Product',
        'uri' => '\/admin\/catalog\/product\/validate\/set\/4\/type\/downloadable\/',
        'title' => 'Admin Create Product - New Downloadable Product Validate',
        'scenario' => 'Admin - Create Product',
    ],
    [
        'label' => 'Admin - Save New Downloadable Product',
        'uri' => '\/admin\/catalog\/product\/save\/set\/4\/type\/downloadable'
                . '\/back\/edit\/active_tab\/product-details\/',
        'title' => 'Admin Create Product - New Downloadable Product Save',
        'scenario' => 'Admin - Create Product',
    ],
    [
        'label' => 'Admin - Create New Simple Product',
        'uri' => '\/admin\/catalog\/product\/new\/set\/4\/type\/simple\/',
        'title' => 'Admin Create Product - New Simple Product$',
        'scenario' => 'Admin - Create Product',
    ],
    [
        'label' => 'Admin - Validate New Simple Product',
        'uri' => '\/admin\/catalog\/product\/validate\/set\/4\/',
        'title' => 'Admin Create Product - New Simple Product Validate',
        'scenario' => 'Admin - Create Product',
    ],
    [
        'label' => 'Admin - Save New Simple Product',
        'uri' => '\/admin\/catalog\/product\/save\/set\/4\/type\/simple\/back\/edit\/active_tab\/product-details\/',
        'title' => 'Admin Create Product - New Simple Product Save',
        'scenario' => 'Admin - Create Product',
    ],
    [
        'label' => 'Admin - Open Category',
        'uri' => '\/admin\/catalog\/category\/',
        'title' => 'Admin Category Management - Landing Page',
        'scenario' => 'Admin - Category Management',
    ],
    [
        'label' => 'Admin - Edit Category',
        'uri' => '\/admin\/catalog\/category\/edit\/id\/',
        'title' => 'Admin Category Management - Select (?:parent|created) category',
        'scenario' => 'Admin - Category Management',
    ],
    [
        'label' => 'Admin - Open New Category Page',
        'uri' => '\/admin\/catalog\/category\/add\/store\/0\/parent\/',
        'title' => 'Admin Category Management - Open new category page',
        'scenario' => 'Admin - Category Management',
    ],
    [
        'label' => 'Admin - Create Empty Category',
        'uri' => '\/admin\/catalog\/category\/save\/',
        'title' => 'Admin Category Management - Create empty category',
        'scenario' => 'Admin - Category Management',
    ],
    [
        'label' => 'Admin - Add Products To Category',
        'uri' => '\/admin\/merchandiser\/position\/save\/',
        'title' => 'Admin Category Management - Add products',
        'scenario' => 'Admin - Category Management',
    ],
    [
        'label' => 'Admin - Verify Products Added To Category',
        'uri' => '\/admin\/merchandiser\/category\/grid\/id\/',
        'title' => 'Admin Category Management - Verify products added',
        'scenario' => 'Admin - Category Management',
    ],
    [
        'label' => 'Admin - Save Category With Products',
        'uri' => '\/admin\/catalog\/category\/save\/',
        'title' => 'Admin Category Management - Save category',
        'scenario' => 'Admin - Category Management',
    ],
    [
        'label' => 'Admin - Move Category',
        'uri' => '\/admin\/catalog\/category\/move\/',
        'title' => 'Admin Category Management - Move category',
        'scenario' => 'Admin - Category Management',
    ],
    [
        'label' => 'Admin - Delete Category',
        'uri' => '\/admin\/catalog\/category\/delete\/id\/',
        'title' => 'Admin Category Management - Delete category',
        'scenario' => 'Admin - Category Management',
    ],
    [
        'label' => 'Admin - Open Promotions Page',
        'uri' => '\/admin\/sales_rule\/promo_quote\/$',
        'title' => 'Admin Promotions Management - Landing Page',
        'scenario' => 'Admin - Promotion Rules',
    ],
    [
        'label' => 'Admin - Create New Promotion Rule',
        'uri' => '\/admin\/sales_rule\/promo_quote\/new$',
        'title' => 'Admin Promotions Management - Create New$',
        'scenario' => 'Admin - Promotion Rules',
    ],
    [
        'label' => 'Admin - Create New Condition For Promotion Rule',
        'uri' => '\/admin\/sales_rule\/promo_quote\/newConditionHtml\/form\/sales_rule_formrule_conditions_fieldset_'
                . '\/form_namespace\/sales_rule_form',
        'title' => 'Admin Promotions Management - Create New Conditional',
        'scenario' => 'Admin - Promotion Rules',
    ],
    [
        'label' => 'Admin - Save Promotion Rule',
        'uri' => '\/admin\/sales_rule\/promo_quote\/save\/',
        'title' => 'Admin Promotions Management - Save$',
        'scenario' => 'Admin - Promotion Rules',
    ],
    [
        'label' => 'API - Create Invoice',
        'uri' => '\/rest\/default\/V1\/order\/\d+\/invoice',
        'title' => 'API - Create Invoice',
        'scenario' => 'Admin - Process Orders',
    ],
    [
        'label' => 'API - Create Shipment',
        'uri' => '\/rest\/default\/V1\/order\/\d+\/ship',
        'title' => 'API - Create Shipment',
        'scenario' => 'Admin - Process Orders',
    ],
    [
        'label' => 'Admin - Open Orders Grid',
        'uri' => '\/admin\/mui\/index\/render\/\?namespace=sales_order_grid',
        'title' => 'Admin Edit Order - Open Orders',
        'scenario' => 'Admin - Create/Process Returns',
    ],
    [
        'label' => 'Admin - Open Orders Grid With Filter',
        'uri' => '\/admin\/mui\/index\/render\/\?namespace=sales_order_grid',
        'title' => 'Admin Edit Order - Search Pending Orders Limit',
        'scenario' => 'Admin - Create/Process Returns',
    ],
    [
        'label' => 'Admin - Open Orders Page',
        'uri' => '\/admin\/sales\/order\/$',
        'title' => 'Admin Edit Order - Orders Page',
        'scenario' => 'Admin - Create/Process Returns',
    ],
    [
        'label' => 'Admin - Open Order',
        'uri' => '\/admin\/sales\/order\/view\/order_id\/',
        'title' => 'Admin Edit Order - Open Order$',
        'scenario' => 'Admin - Create/Process Returns',
    ],
    [
        'label' => 'Admin - Start Invoicing',
        'uri' => '\/admin\/sales\/order_invoice\/start\/order_id\/',
        'title' => 'Admin Edit Order - Invoice Start',
        'scenario' => 'Admin - Create/Process Returns',
    ],
    [
        'label' => 'Admin - Submit Invoice',
        'uri' => '\/admin\/sales\/order_invoice\/save\/order_id\/',
        'title' => 'Admin Edit Order - Invoice Submit',
        'scenario' => 'Admin - Create/Process Returns',
    ],
    [
        'label' => 'Admin - Start Credit Memo',
        'uri' => '\/admin\/sales\/order_creditmemo\/start\/order_id\/',
        'title' => 'Admin Edit Order - Credit Memo Start',
        'scenario' => 'Admin - Create/Process Returns',
    ],
    [
        'label' => 'Admin - Submit Credit Memo',
        'uri' => '\/admin\/sales\/order_creditmemo\/save\/order_id\/',
        'title' => 'Admin Edit Order - Credit Memo Submit',
        'scenario' => 'Admin - Create/Process Returns',
    ],
    [
        'label' => 'Admin - Search Order By Increment Id',
        'uri' => '\/admin\/mui\/index\/render\/\?namespace=sales_order_grid.*filters\%5Bincrement_id\%5D',
        'title' => 'Admin Edit Order - Search Orders$',
        'scenario' => 'Admin - Create/Process Returns',
    ],
    [
        'label' => 'Admin - Open Negotiable Quote',
        'uri' => '\/admin\/quotes\/quote\/view\/quote_id\/',
        'title' => 'Admin - Open Quote',
        'scenario' => 'Admin - Process Negotiable Quotes',
    ],
    [
        'label' => 'Admin - Update Negotiable Quote On Open',
        'uri' => '\/admin\/quotes\/quote\/updateOnOpen\/\?isAjax=true',
        'title' => 'Admin - Update Quote On Open',
        'scenario' => 'Admin - Process Negotiable Quotes',
    ],
    [
        'label' => 'Admin - Send Negotiable Quote',
        'uri' => '\/admin\/quotes\/quote\/send\/quote_id\/',
        'title' => 'Admin - Send Quote',
        'scenario' => 'Admin - Process Negotiable Quotes',
    ],
    [
        'label' => 'Admin - Open Shared Catalogs Grid',
        'uri' => '\/admin\/shared_catalog\/sharedCatalog\/index\/',
        'title' => 'Admin - Open Shared Catalogs$',
        'scenario' => 'Admin - Create Shared Catalog',
    ],
    [
        'label' => 'Admin - Open New Shared Catalog Page',
        'uri' => '\/admin\/shared_catalog\/sharedCatalog\/create\/',
        'title' => 'Admin - Open Create Shared Catalog',
        'scenario' => 'Admin - Create Shared Catalog',
    ],
    [
        'label' => 'Admin - Save Shared Catalog',
        'uri' => '\/admin\/shared_catalog\/sharedCatalog\/save\/',
        'title' => 'Admin - Create Shared Catalog',
        'scenario' => 'Admin - Create Shared Catalog',
    ],
    [
        'label' => 'Admin - Shared Catalogs Grid Renderer',
        'uri' => '\/admin\/mui\/index\/render\/\?namespace=shared_catalog_listing',
        'title' => 'Admin - Open Shared Catalogs Grid',
        'scenario' => 'Admin - Create Shared Catalog',
    ],
    [
        'label' => 'Admin - Open Shared Catalog Companies Grid',
        'uri' => '\/admin\/shared_catalog\/sharedCatalog\/companies\/shared_catalog_id\/',
        'title' => 'Admin - Open Assign Companies$',
        'scenario' => 'Admin - Create Shared Catalog',
    ],
    [
        'label' => 'Admin - Validate Shared Catalog Companies',
        'uri' => '\/admin\/shared_catalog\/sharedCatalog\/company_massAssign_validate\/shared_catalog_id\/',
        'title' => 'Admin - Open Assign Companies - Validate',
        'scenario' => 'Admin - Create Shared Catalog',
    ],
    [
        'label' => 'Admin - Assign Companies To Shared Catalog Mass Action',
        'uri' => '\/admin\/shared_catalog\/sharedCatalog\/company_massAssign\/shared_catalog_id\/',
        'title' => 'Admin - Open Assign Companies - Mass Assign',
        'scenario' => 'Admin - Create Shared Catalog',
    ],
    [
        'label' => 'Admin - Save Assigned Companies',
        'uri' => '\/admin\/shared_catalog\/sharedCatalog\/company_save\/shared_catalog_id\/',
        'title' => 'Admin - Open Assign Companies - Save',
        'scenario' => 'Admin - Create Shared Catalog',
    ],
    [
        'label' => 'Admin - Open Shared Catalog Wizard',
        'uri' => '\/admin\/shared_catalog\/sharedCatalog\/wizard\/shared_catalog_id\/',
        'title' => 'Admin - Open Shared Catalog Pricing and Structure$',
        'scenario' => 'Admin - Create Shared Catalog',
    ],
    [
        'label' => 'Admin - Open Shared Catalog Products Grid',
        'uri' => '\/admin\/mui\/index\/render\/configure_key\/',
        'title' => 'Admin - Open Shared Catalog Pricing and Structure - Product Listing Structure',
        'scenario' => 'Admin - Create Shared Catalog',
    ],
    [
        'label' => 'Admin - Get Shared Catalog Tree Structure',
        'uri' => '\/admin\/shared_catalog\/sharedCatalog\/configure_tree_structure_get\/id\/',
        'title' => 'Admin - Open Shared Catalog Pricing and Structure - Configure Tree .*',
        'scenario' => 'Admin - Create Shared Catalog',
    ],
    [
        'label' => 'Admin - Assign Products To Shared Catalog Mass Action',
        'uri' => '\/admin\/shared_catalog\/sharedCatalog\/configure_product_massAssign\/shared_catalog_id\/',
        'title' => 'Admin - Open Shared Catalog Pricing and Structure - Configure Product Mass Assign',
        'scenario' => 'Admin - Create Shared Catalog',
    ],
    [
        'label' => 'Admin - Open Shared Catalog Pricing Grid',
        'uri' => '\/admin\/mui\/index\/render\/id\/\d+\/configure_key\/',
        'title' => 'Admin - Open Shared Catalog Pricing and Structure - Product Listing Pricing',
        'scenario' => 'Admin - Create Shared Catalog',
    ],
    [
        'label' => 'Admin - Configure Shared Catalog Product Price Discount',
        'uri' => '\/admin\/shared_catalog\/sharedCatalog\/configure_product_price_discount\/shared_catalog_id\/',
        'title' => 'Admin - Open Shared Catalog Pricing and Structure - Configure Product Price Discount',
        'scenario' => 'Admin - Create Shared Catalog',
    ],
    [
        'label' => 'Admin - Save Shared Catalog Configuration',
        'uri' => '\/admin\/shared_catalog\/sharedCatalog\/configure_save\/shared_catalog_id\/',
        'title' => 'Admin - Open Shared Catalog Pricing and Structure - Save',
        'scenario' => 'Admin - Create Shared Catalog',
    ],
];
